// <auto-generated />
namespace Growth.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class add_photo_property : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(add_photo_property));
        
        string IMigrationMetadata.Id
        {
            get { return "201704191723101_add_photo_property"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
